### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by honungsburk** [miukimiu/react-kawaii#114]
To install `react-kawaii` when using the two latest major releases of react requires you to use `npm install react-kawaii --legacy-peer-deps`. It would be great if we could bump dependency requirements so it can be installed by `npm install react-kawaii`. I can supply a PR!

**Comment by miukimiu** [comment]
Hi @honungsburk. That would be great. Let me know when the PR is ready.

**Comment by italodeandra** [comment]
https://github.com/miukimiu/react-kawaii/pull/113
