### ISSUE TITLE
Cute Favicon missing 🦕

### ISSUE THREAD

**Issue by elbotho** [miukimiu/react-kawaii#117]
It's hard to accept that the cutest docs ever don't have a dino favicon 😸

![image](https://user-images.githubusercontent.com/1258870/183151227-58a05311-6216-4f12-a32b-5ec7a013e0ae.png)

**Comment by miukimiu** [comment]
Done! 👍🏽 

<img width="234" alt="Screenshot 2024-06-09 at 21 25 59" src="https://github.com/miukimiu/react-kawaii/assets/2750668/c1b718a0-0655-44a0-9060-a0eb96d7dbb0">
