### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by omriluz** [miukimiu/react-kawaii#131]
Hey since React 18.3 is removed defaultProps, I would think it will be better to change it to regular javascript default params so the error would go away, I am okay with working on it if you assign it to me.

**Comment by miukimiu** [comment]
Thanks, @omriluz. I might change everything to TS.

**Comment by miukimiu** [comment]
@omriluz the PR that introduces TS is in progress: https://github.com/miukimiu/react-kawaii/pull/132. 

Let me know if you want to help. 🎉

**Comment by omriluz** [comment]
@miukimiu  hey yeah i want to!

**Comment by miukimiu** [comment]
@omriluz I pushed the changes that introduce TS. If you find any issues let me know. 😄 

Feel free to contribute/open a PR with code enhancements for the website or the package. 🎉
