### ISSUE TITLE
The Speech is not working as expected

### ISSUE THREAD

**Issue by miukimiu** [miukimiu/react-kawaii#22]
The Speech Bubble is not working as expected.

![screen shot 2018-04-24 at 5 15 57 pm](https://user-images.githubusercontent.com/2750668/39200160-41892b0e-47e3-11e8-95a4-331f455c43de.png)

**Comment by yuanchuan** [comment]
I'd like to help.
Do you have an online demo of this screenshot?

**Comment by SaraVieira** [comment]
I'm here! Hello 👋

I can't see the problem in the code sandbox tho :(

**Comment by miukimiu** [comment]
@SaraVieira it happens when you hover the Kawaii.

**Comment by SaraVieira** [comment]
OHHHH! I'm on my phone, I'll check when I am on the computer :)
