### ISSUE TITLE
More components? 

### ISSUE THREAD

**Issue by SaraVieira** [miukimiu/react-kawaii#3]
Hi! 

This is amazing! 

Are you gonna make any more components? Want help?

**Comment by miukimiu** [comment]
Hi @SaraVieira,
Yes, the idea is to create more components. 

I would love to have some help. Do you want to help?

**Comment by SaraVieira** [comment]
Nice! 

Yes, I would love to! Any ideas?

**Comment by miukimiu** [comment]
I think the components can have an animation. Besides the size, mood and color props it can have a prop to activate the animation. If this prop is set to true then the component is animated. 

I don't have any idea for which type of animation. It can be a slight movement always happening or on hover, something happens... CSS or JS... 

Do you want to try something?

**Comment by SaraVieira** [comment]
Sure, I would go with the mouth and eyes slightly moving up and down I think that gives him some personality. 

Also we could see a text prop that would show as a speech bubble on hover? What do you think?

**Comment by miukimiu** [comment]
Yes. Perfect! Go for it! 😄

**Comment by SaraVieira** [comment]
On it!

**Comment by SaraVieira** [comment]
Look at these adorable animals : http://www.flaticon.com/packs/kawaii-animals-2 🐻 🎉

**Comment by miukimiu** [comment]
Merged! 😸

**Comment by SaraVieira** [comment]
Awesome ! I'll start with the planet 😄
