### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by miukimiu** [miukimiu/react-kawaii#34]
Design:
https://invis.io/ASMQP3GD8TB#/293382879_React-Kawaii_Landing

**Comment by miukimiu** [comment]
@codenakama one part of the landing page is missing: the "Contribute" section: https://invis.io/ASMQP3GD8TB#/293382879_React-Kawaii_Landing

Also, we need more demos. And I think the "animation" section should be animated.

Do you want to help with any of these tasks?

**Comment by codenakama** [comment]
@miukimiu sorry for delay replying. back from my trip. Yes I'd like to help! probably this weekend I can look into these tasks. Let me know of any more details I should need. 

Contribute section - what is outstanding apart from the design? Who are the contributors at the moment?

ANimate section - does it show the code on the right side?

**Comment by codenakama** [comment]
@miukimiu I will try to add some pull requests over the weekend then :)

**Comment by codenakama** [comment]
@miukimiu can't push to branch due to permissions.
