### ISSUE TITLE
TypeScript declaration files

### ISSUE THREAD

**Issue by nolanpather** [miukimiu/react-kawaii#60]
Hi,

I have been adding some "kawaii-ness" to a typescript project that I am working on, but have run into a small problem - there is no TypeScript declaration file for react-kawaii. I have built a custom declaration file that defines only the components that I am using as a work-around. Are there any plans to add a declaration file in the near future?

**Comment by miukimiu** [comment]
Hi,

I never thought about it. But I asked a friend of mine that works with typescript to give it a look. 

Probably this change is going to be implemented in the next release that will also give support to react-native.

**Comment by nolanpather** [comment]
OK, sounds good. Looking forward to the future updates 👍
