### ISSUE TITLE
Add support for server side rendered apps

### ISSUE THREAD

**Issue by codenakama** [miukimiu/react-kawaii#62]
Currently the package blows up when importing on a server-side rendered framework such as Nextjs.
`ReferenceError: window is not defined`

I am also curious about the dependency on the window object considering that its just a "dumb" component. @miukimiu I'll investigate this soon.

**Comment by codenakama** [comment]
fixed by #63

**Comment by raitucarp** [comment]
https://github.com/miukimiu/react-kawaii/pull/63#issuecomment-895714503
