### ISSUE TITLE
Shouldn't the kawaii face be a separated component ?

### ISSUE THREAD

**Issue by JoaoMosmann** [miukimiu/react-kawaii#7]
I understand that some character might have different faces. But for those that share the same, it would be good to have a separated component to avoid duplicated code.

If there isn't a reason to each character having its own implementation, I would gladly do a PR for it.

**Comment by miukimiu** [comment]
There's no reason for that. Indeed the code could be much better if we could avoid the code duplication.

You can create a PR for that. It would be very helpful.
